export interface PlatformSettingsPatch {
  appInstanceName?: string;
  movieRootPath?: string;
  seriesRootPath?: string;
  downloadsPath?: string;
  incompleteDownloadsPath?: string;
  autoStartJobs?: boolean;
  enableNotifications?: boolean;
  renameOnImport?: boolean;
  useHardlinks?: boolean;
  cleanupEmptyFolders?: boolean;
  removeCompletedDownloads?: boolean;
  unmonitorWhenCutoffMet?: boolean;
  movieFolderFormat?: string;
  seriesFolderFormat?: string;
  episodeFileFormat?: string;
  hostBindAddress?: string;
  hostPort?: number;
  urlBase?: string;
  requireAuthentication?: boolean;
  uiTheme?: string;
  uiDensity?: string;
  uiColorMode?: string;
  uiLanguage?: string;
  calendarFirstDayOfWeek?: string;
  calendarWeekHeaderFormat?: string;
  runtimeFormat?: string;
  shortDateFormat?: string;
  longDateFormat?: string;
  timeFormat?: string;
  showRelativeDates?: boolean;
  defaultMovieView?: string;
  defaultShowView?: string;
  metadataNfoEnabled?: boolean;
  metadataArtworkEnabled?: boolean;
  metadataCertificationCountry?: string;
  metadataLanguage?: string;
  metadataProviderMode?: string;
  metadataBrokerUrl?: string;
  metadataTmdbApiKey?: string;
  metadataOmdbApiKey?: string;
  releaseNeverGrabPatterns?: string;
  searchScoringMode?: string;
  importRecoveryRetentionDays?: number;
  libraryFileCheckHours?: number;
  mdbListApiKey?: string;
  downloadHealthStrikeThreshold?: number;
  cleanupBlockReleaseAfterThreshold?: boolean;
  cleanupQueueReplacementAfterThreshold?: boolean;
  cleanupRemoveClientEntryAfterThreshold?: boolean;
  cleanupPurgePayloadAfterThreshold?: boolean;
  sharingMode?: string;
  /** Null clears that half of the rule; undefined leaves it as it is. */
  sharingForHours?: number | null;
  sharingUntilRatio?: number | null;
  sharingStuckAction?: string;
  sharingStuckAfterDays?: number;
}
