namespace Deluno.Platform.Contracts;

public sealed record IntakeSourceItem(
    string Id,
    string Name,
    string Provider,
    string FeedUrl,
    string MediaType,
    string? LibraryId,
    string? LibraryName,
    string? QualityProfileId,
    string? QualityProfileName,
    string RequiredGenres,
    double? MinimumRating,
    int? MinimumYear,
    int? MaximumAgeDays,
    string AllowedCertifications,
    string Audience,
    int SyncIntervalHours,
    DateTimeOffset? LastSyncUtc,
    string LastSyncStatus,
    string? LastSyncSummary,
    bool SearchOnAdd,
    bool IsEnabled,
    DateTimeOffset CreatedUtc,
    DateTimeOffset UpdatedUtc);
