namespace Deluno.Platform.Contracts;

public sealed record PlatformSettingsSnapshot(
    string AppInstanceName,
    string? MovieRootPath,
    string? SeriesRootPath,
    string? DownloadsPath,
    string? IncompleteDownloadsPath,
    bool AutoStartJobs,
    bool EnableNotifications,
    bool RenameOnImport,
    bool UseHardlinks,
    bool CleanupEmptyFolders,
    bool RemoveCompletedDownloads,
    bool UnmonitorWhenCutoffMet,
    string MovieFolderFormat,
    string SeriesFolderFormat,
    string EpisodeFileFormat,
    string HostBindAddress,
    int HostPort,
    string UrlBase,
    bool RequireAuthentication,
    string UiTheme,
    string UiDensity,
    string DefaultMovieView,
    string DefaultShowView,
    bool MetadataNfoEnabled,
    bool MetadataArtworkEnabled,
    string MetadataCertificationCountry,
    string MetadataLanguage,
    string MetadataProviderMode,
    string MetadataBrokerUrl,
    bool MetadataBrokerConfigured,
    bool MetadataTmdbApiKeyConfigured,
    bool MetadataOmdbApiKeyConfigured,
    string ReleaseNeverGrabPatterns,
    string SearchScoringMode,
    int ImportRecoveryRetentionDays,
    DateTimeOffset UpdatedUtc,
    bool MdbListApiKeyConfigured = false,
    int DownloadHealthStrikeThreshold = 3,
    bool CleanupBlockReleaseAfterThreshold = true,
    bool CleanupQueueReplacementAfterThreshold = true,
    bool CleanupRemoveClientEntryAfterThreshold = false,
    bool CleanupPurgePayloadAfterThreshold = false,
    bool WorkflowVerified = false,
    // What Deluno does with the download client's copy once a title is safely
    // in the library (#288). Sits with the cleanup settings above because it is
    // the same question — what happens on its own, without being asked.
    string SharingMode = SharingPolicy.ModeShareThenTidy,
    int? SharingForHours = 72,
    double? SharingUntilRatio = null,
    string SharingStuckAction = SharingPolicy.StuckGiveUp,
    int SharingStuckAfterDays = 14,
    string UiColorMode = "standard",
    string UiLanguage = "en-AU",
    string CalendarFirstDayOfWeek = "monday",
    string CalendarWeekHeaderFormat = "ddd d/M",
    string RuntimeFormat = "hoursMinutes",
    string ShortDateFormat = "dmy",
    string LongDateFormat = "full",
    string TimeFormat = "12",
    bool ShowRelativeDates = true,
    // How often Deluno looks at whether the files it thinks you have are still
    // on disk. Configurable because the right answer depends on the disk: a
    // local pool can afford hourly; a NAS that spins up to answer should not be
    // woken every hour to be asked. DESIGN-007, the console's third section.
    int LibraryFileCheckHours = 6);
