namespace Deluno.Platform.Contracts;

public sealed record UpdatePlatformSettingsRequest(
    string? AppInstanceName,
    string? MovieRootPath,
    string? SeriesRootPath,
    string? DownloadsPath,
    string? IncompleteDownloadsPath,
    bool AutoStartJobs,
    bool EnableNotifications,
    bool RenameOnImport,
    bool UseHardlinks,
    bool CleanupEmptyFolders,
    bool RemoveCompletedDownloads,
    bool UnmonitorWhenCutoffMet,
    string? MovieFolderFormat,
    string? SeriesFolderFormat,
    string? EpisodeFileFormat,
    string? HostBindAddress,
    int HostPort,
    string? UrlBase,
    bool RequireAuthentication,
    string? UiTheme,
    string? UiDensity,
    string? DefaultMovieView,
    string? DefaultShowView,
    bool MetadataNfoEnabled,
    bool MetadataArtworkEnabled,
    string? MetadataCertificationCountry,
    string? MetadataLanguage,
    string? MetadataProviderMode,
    string? MetadataBrokerUrl,
    string? MetadataTmdbApiKey,
    string? MetadataOmdbApiKey,
    string? ReleaseNeverGrabPatterns,
    string? SearchScoringMode = null,
    int? ImportRecoveryRetentionDays = null);
