using Deluno.Quality.Contracts;
using Deluno.Quality.Scenarios;

namespace Deluno.Persistence.Tests.Quality;

public sealed class MediaPlanScenarioPlanIdentityTests
{
    [Fact]
    public void Dual_scope_scenario_matches_only_its_own_media_plan()
    {
        var moviePlan = Plan("movies", new MediaPlanAutomationIntent("family-1080p", 1));
        var tvPlan = Plan("tv", new MediaPlanAutomationIntent("family-1080p", 1));

        Assert.True(MediaPlanScenarioPlanIdentity.Matches(moviePlan, "family-1080p", "movies"));
        Assert.False(MediaPlanScenarioPlanIdentity.Matches(moviePlan, "family-1080p", "tv"));
        Assert.True(MediaPlanScenarioPlanIdentity.Matches(tvPlan, "family-1080p", "TV shows"));
    }

    [Fact]
    public void Legacy_marker_fallback_is_exact_and_still_scoped_to_media_type()
    {
        var legacyMoviePlan = Plan(
            "movies",
            automationIntent: null,
            notes: "Scenario: family-1080p v1\nGenerated by Deluno.");

        Assert.True(MediaPlanScenarioPlanIdentity.Matches(legacyMoviePlan, "family-1080p", "movies"));
        Assert.False(MediaPlanScenarioPlanIdentity.Matches(legacyMoviePlan, "family", "movies"));
        Assert.False(MediaPlanScenarioPlanIdentity.Matches(legacyMoviePlan, "family-1080p", "tv"));
    }

    private static PolicySetItem Plan(
        string mediaType,
        MediaPlanAutomationIntent? automationIntent,
        string? notes = null)
        => new(
            "plan-1",
            "Plan",
            mediaType,
            null,
            null,
            null,
            null,
            string.Empty,
            null,
            null,
            true,
            true,
            notes,
            DateTimeOffset.UtcNow,
            DateTimeOffset.UtcNow,
            automationIntent);
}
